name: Ruby

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby version specified in `.ruby-version`
      with:
          ruby-version: 2.6.6
      uses: eregon/use-ruby-action@master

    - name: Install dependencies
      run:  bundle install --jobs 4 --retry 3

    - name: Run Rubocop
      env:
        RAILS_ENV: test
      run: bundle exec rubocop --config .rubocop.yml

    - name: Run tests with RSpec
      env:
        RAILS_ENV: test
      run: bundle exec rspec
